version: '3.5'
services:
  mariadb:
    image: mariadb
    container_name: databse-mysql
    restart: always
    ports:
      - 8889:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress
  phpmyadmin:
    container_name: php-myadmin
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
    networks:
      - wordpress
  wordpress:
    container_name: website-wordpress
    depends_on:
      - mariadb
    image: wordpress:latest
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
    ports:
      - "8096:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress

networks:
  wordpress:
    name: wordpress